export enum FightMethod {
  KO = 'KO',
  TKO = 'TKO',
  SUBMISSION = 'SUBMISSION',
  UNANIMOUS_DECISION = 'UNANIMOUS_DECISION',
  SPLIT_DECISION = 'SPLIT_DECISION',
  MAJORITY_DECISION = 'MAJORITY_DECISION',
  DRAW = 'DRAW',
  NO_CONTEST = 'NO_CONTEST',
  DISQUALIFICATION = 'DISQUALIFICATION',
}