import { DeepPartial } from 'typeorm';
import { Fighter } from '../../fighters/entities/fighter.entity';
import { WeightClass } from '../../fighters//enums//weight-class.enum';

export const fightersSeedData: DeepPartial<Fighter>[] = [
  {
    name: 'Jon Jones',
    nickname: 'Bones',
    country: 'United States',
    age: 39,
    height: 193,
    weight: 112,
    weightClass: WeightClass.HEAVYWEIGHT,
    reach: 213,
    stance: 'Orthodox',
    fightingStyle: 'Wrestling / Muay Thai',
    bio: 'Former UFC light heavyweight champion and UFC heavyweight champion, known for creative striking, elite wrestling and strong fight IQ.',

    wins: 28,
    losses: 1,
    draws: 0,
    koWins: 11,
    submissionWins: 7,
    decisionWins: 10,
    currentWinStreak: 2,

    strikingAccuracy: 58,
    strikingDefense: 64,
    significantStrikesPerMinute: 4.29,
    significantStrikesAbsorbedPerMinute: 2.22,

    takedownAccuracy: 44,
    takedownDefense: 95,
    takedownsPer15: 1.85,
    submissionAverage: 0.5,

    ranking: 0,
    champion: false,
    interimChampion: false
  },
  {
    name: 'Stipe Miocic',
    nickname: '',
    country: 'United States',
    age: 43,
    height: 193,
    weight: 109,
    weightClass: WeightClass.HEAVYWEIGHT,
    reach: 203,
    stance: 'Orthodox',
    fightingStyle: 'Boxing / Wrestling',
    bio: 'Former UFC heavyweight champion known for boxing, wrestling, durability and victories over several heavyweight champions.',

    wins: 20,
    losses: 5,
    draws: 0,
    koWins: 15,
    submissionWins: 0,
    decisionWins: 5,
    currentWinStreak: 0,

    strikingAccuracy: 52,
    strikingDefense: 52,
    significantStrikesPerMinute: 4.67,
    significantStrikesAbsorbedPerMinute: 4.01,

    takedownAccuracy: 34,
    takedownDefense: 65,
    takedownsPer15: 1.74,
    submissionAverage: 0,

    ranking: 0,
    champion: false,
    interimChampion: false
  },
  {
    name: 'Charles Oliveira',
    nickname: 'Do Bronxs',
    country: 'Brazil',
    age: 36,
    height: 178,
    weight: 70,
    weightClass: WeightClass.LIGHTWEIGHT,
    reach: 188,
    stance: 'Orthodox',
    fightingStyle: 'Brazilian Jiu-Jitsu / Muay Thai',
    bio: 'Former UFC lightweight champion and elite submission specialist known for aggressive grappling and dangerous striking.',

    wins: 37,
    losses: 11,
    draws: 0,
    koWins: 10,
    submissionWins: 22,
    decisionWins: 5,
    currentWinStreak: 0,

    strikingAccuracy: 55,
    strikingDefense: 48,
    significantStrikesPerMinute: 3.23,
    significantStrikesAbsorbedPerMinute: 3.05,

    takedownAccuracy: 39,
    takedownDefense: 54,
    takedownsPer15: 2.29,
    submissionAverage: 2.6,

    ranking: 0,
    champion: false,
    interimChampion: false
  },
  {
    name: 'Michael Chandler',
    nickname: 'Iron',
    country: 'United States',
    age: 40,
    height: 173,
    weight: 70,
    weightClass: WeightClass.LIGHTWEIGHT,
    reach: 180,
    stance: 'Orthodox',
    fightingStyle: 'Wrestling / Boxing',
    bio: 'Explosive lightweight fighter known for powerful boxing, collegiate wrestling and an aggressive fighting style.',

    wins: 23,
    losses: 11,
    draws: 0,
    koWins: 11,
    submissionWins: 7,
    decisionWins: 5,
    currentWinStreak: 0,

    strikingAccuracy: 49,
    strikingDefense: 43,
    significantStrikesPerMinute: 3.91,
    significantStrikesAbsorbedPerMinute: 4.51,

    takedownAccuracy: 41,
    takedownDefense: 61,
    takedownsPer15: 1.96,
    submissionAverage: 0.6,

    ranking: 0,
    champion: false,
    interimChampion: false
  },
  {
    name: 'Alex Pereira',
    nickname: 'Poatan',
    country: 'Brazil',
    age: 39,
    height: 193,
    weight: 93,
    weightClass: WeightClass.LIGHT_HEAVYWEIGHT,
    reach: 201,
    stance: 'Orthodox',
    fightingStyle: 'Kickboxing',
    bio: 'Former UFC middleweight and light heavyweight champion known for elite kickboxing and exceptional knockout power.',

    wins: 13,
    losses: 4,
    draws: 0,
    koWins: 11,
    submissionWins: 0,
    decisionWins: 2,
    currentWinStreak: 0,

    strikingAccuracy: 62,
    strikingDefense: 50,
    significantStrikesPerMinute: 5.15,
    significantStrikesAbsorbedPerMinute: 3.68,

    takedownAccuracy: 0,
    takedownDefense: 70,
    takedownsPer15: 0,
    submissionAverage: 0,

    ranking: 0,
    champion: false,
    interimChampion: false
  },
  {
    name: 'Jiri Prochazka',
    nickname: 'BJP',
    country: 'Czech Republic',
    age: 33,
    height: 191,
    weight: 93,
    weightClass: WeightClass.LIGHT_HEAVYWEIGHT,
    reach: 203,
    stance: 'Orthodox',
    fightingStyle: 'Muay Thai / Karate',
    bio: 'Former UFC light heavyweight champion known for unorthodox movement, high-volume striking and dramatic finishes.',

    wins: 32,
    losses: 6,
    draws: 1,
    koWins: 26,
    submissionWins: 3,
    decisionWins: 3,
    currentWinStreak: 0,

    strikingAccuracy: 55,
    strikingDefense: 45,
    significantStrikesPerMinute: 5.61,
    significantStrikesAbsorbedPerMinute: 5.67,

    takedownAccuracy: 66,
    takedownDefense: 68,
    takedownsPer15: 0.49,
    submissionAverage: 0.4,

    ranking: 0,
    champion: false,
    interimChampion: false
  },
  {
    name: 'Diego Lopes',
    nickname: '',
    country: 'Brazil',
    age: 31,
    height: 180,
    weight: 66,
    weightClass: WeightClass.FEATHERWEIGHT,
    reach: 183,
    stance: 'Orthodox',
    fightingStyle: 'Brazilian Jiu-Jitsu / Boxing',
    bio: 'Dynamic featherweight known for dangerous submissions, aggressive boxing and a high finishing rate.',

    wins: 28,
    losses: 8,
    draws: 0,
    koWins: 11,
    submissionWins: 12,
    decisionWins: 5,
    currentWinStreak: 0,

    strikingAccuracy: 47,
    strikingDefense: 46,
    significantStrikesPerMinute: 3.79,
    significantStrikesAbsorbedPerMinute: 4.65,

    takedownAccuracy: 40,
    takedownDefense: 35,
    takedownsPer15: 0.82,
    submissionAverage: 1.2,

    ranking: 0,
    champion: false,
    interimChampion: false
  },
  {
    name: 'Dan Ige',
    nickname: '50K',
    country: 'United States',
    age: 34,
    height: 170,
    weight: 66,
    weightClass: WeightClass.FEATHERWEIGHT,
    reach: 180,
    stance: 'Orthodox',
    fightingStyle: 'Boxing / Wrestling',
    bio: 'Durable featherweight contender known for boxing combinations, strong takedown defense and willingness to accept difficult fights.',

    wins: 19,
    losses: 11,
    draws: 0,
    koWins: 5,
    submissionWins: 5,
    decisionWins: 9,
    currentWinStreak: 0,

    strikingAccuracy: 45,
    strikingDefense: 56,
    significantStrikesPerMinute: 3.60,
    significantStrikesAbsorbedPerMinute: 3.56,

    takedownAccuracy: 26,
    takedownDefense: 59,
    takedownsPer15: 0.93,
    submissionAverage: 0.3,

    ranking: 0,
    champion: false,
    interimChampion: false
  },
  {
    name: 'Islam Makhachev',
    nickname: '',
    country: 'Russia',
    age: 34,
    height: 178,
    weight: 70,
    weightClass: WeightClass.LIGHTWEIGHT,
    reach: 179,
    stance: 'Southpaw',
    fightingStyle: 'Sambo / Wrestling',
    bio: 'Elite grappler known for dominant control, efficient striking, takedowns and submission skills.',

    wins: 28,
    losses: 1,
    draws: 0,
    koWins: 5,
    submissionWins: 13,
    decisionWins: 10,
    currentWinStreak: 0,

    strikingAccuracy: 58,
    strikingDefense: 61,
    significantStrikesPerMinute: 2.45,
    significantStrikesAbsorbedPerMinute: 1.45,

    takedownAccuracy: 56,
    takedownDefense: 91,
    takedownsPer15: 3.10,
    submissionAverage: 1.1,

    ranking: 0,
    champion: false,
    interimChampion: false
  },
  {
    name: 'Dustin Poirier',
    nickname: 'The Diamond',
    country: 'United States',
    age: 37,
    height: 175,
    weight: 70,
    weightClass: WeightClass.LIGHTWEIGHT,
    reach: 183,
    stance: 'Southpaw',
    fightingStyle: 'Boxing / Brazilian Jiu-Jitsu',
    bio: 'Former interim UFC lightweight champion known for elite boxing combinations, durability and extensive championship experience.',

    wins: 30,
    losses: 10,
    draws: 0,
    koWins: 16,
    submissionWins: 8,
    decisionWins: 6,
    currentWinStreak: 0,

    strikingAccuracy: 50,
    strikingDefense: 52,
    significantStrikesPerMinute: 5.24,
    significantStrikesAbsorbedPerMinute: 4.57,

    takedownAccuracy: 35,
    takedownDefense: 64,
    takedownsPer15: 1.15,
    submissionAverage: 1.2,

    ranking: 0,
    champion: false,
    interimChampion: false
  },
  {
    name: 'Sean Strickland',
    nickname: 'Tarzan',
    country: 'United States',
    age: 35,
    height: 185,
    weight: 84,
weightClass: WeightClass.MIDDLEWEIGHT,
    reach: 193,
    stance: 'Orthodox',
    fightingStyle: 'Boxing',
    bio: 'Former UFC middleweight champion known for pressure boxing, defensive awareness and a high-volume jab.',

    wins: 31,
    losses: 7,
    draws: 0,
    koWins: 12,
    submissionWins: 4,
    decisionWins: 15,
    currentWinStreak: 0,

    strikingAccuracy: 42,
    strikingDefense: 60,
    significantStrikesPerMinute: 5.98,
    significantStrikesAbsorbedPerMinute: 4.53,

    takedownAccuracy: 64,
    takedownDefense: 84,
    takedownsPer15: 0.66,
    submissionAverage: 0.1,

    ranking: 0,
    champion: false,
    interimChampion: false
  },
  {
    name: 'Paulo Costa',
    nickname: 'The Eraser',
    country: 'Brazil',
    age: 35,
    height: 185,
    weight: 84,
    weightClass: WeightClass.MIDDLEWEIGHT,
    reach: 183,
    stance: 'Orthodox',
    fightingStyle: 'Kickboxing / Brazilian Jiu-Jitsu',
    bio: 'Powerful middleweight known for aggressive pressure, body attacks and high-volume combinations.',

    wins: 16,
    losses: 4,
    draws: 0,
    koWins: 12,
    submissionWins: 1,
    decisionWins: 3,
    currentWinStreak: 0,

    strikingAccuracy: 59,
    strikingDefense: 49,
    significantStrikesPerMinute: 6.15,
    significantStrikesAbsorbedPerMinute: 5.96,

    takedownAccuracy: 42,
    takedownDefense: 77,
    takedownsPer15: 0.30,
    submissionAverage: 0,

    ranking: 0,
    champion: false,
    interimChampion: false
  }
];